<?php
/**
 * Created by PhpStorm.
 * User: lfq
 * Date: 2019/3/17
 * Time: 7:30 AM
 */

namespace app\admin\controller;

use think\Controller;

class City extends Controller
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function _empty($name){
        $this->showCity($name);
    }

    public function showCity($name){
        return '当前城市'.$name;
    }
}
